import type { FunnelPage, Template } from "@shared/schema";

export const defaultTemplates: Template[] = [
  {
    id: "template-lead-gen",
    name: "Lead-Generierung",
    description: "Sammle qualifizierte Leads mit einem mehrstufigen Funnel",
    category: "leads",
    thumbnail: "/templates/lead-gen.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Bereit für mehr Kunden?",
        subtitle: "Entdecke, wie wir dein Business auf das nächste Level bringen",
        elements: [],
        buttonText: "Jetzt starten",
        backgroundColor: "#7C3AED",
      },
      {
        id: "page-2",
        type: "question",
        title: "Was ist deine größte Herausforderung?",
        elements: [],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "contact",
        title: "Lass uns sprechen!",
        subtitle: "Trage deine Kontaktdaten ein",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
          { id: "el-3", type: "input", placeholder: "Deine Telefonnummer" },
        ],
        buttonText: "Absenden",
      },
      {
        id: "page-4",
        type: "thankyou",
        title: "Vielen Dank!",
        subtitle: "Wir melden uns innerhalb von 24 Stunden bei dir",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#7C3AED",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-webinar",
    name: "Webinar-Anmeldung",
    description: "Maximiere die Anmeldungen für dein Webinar",
    category: "webinar",
    thumbnail: "/templates/webinar.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Kostenloses Webinar",
        subtitle: "Lerne die Geheimnisse erfolgreicher Unternehmer",
        elements: [],
        buttonText: "Jetzt anmelden",
        backgroundColor: "#2563EB",
      },
      {
        id: "page-2",
        type: "contact",
        title: "Sichere dir deinen Platz",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "Platz reservieren",
      },
      {
        id: "page-3",
        type: "thankyou",
        title: "Du bist dabei!",
        subtitle: "Check deine E-Mails für den Zugangslink",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#2563EB",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-quiz",
    name: "Interaktives Quiz",
    description: "Qualifiziere Leads mit einem unterhaltsamen Quiz",
    category: "quiz",
    thumbnail: "/templates/quiz.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Finde heraus, welcher Typ du bist!",
        subtitle: "Beantworte 3 kurze Fragen",
        elements: [],
        buttonText: "Quiz starten",
        backgroundColor: "#10B981",
      },
      {
        id: "page-2",
        type: "multiChoice",
        title: "Was beschreibt dich am besten?",
        elements: [
          { id: "el-1", type: "radio", options: ["Kreativ", "Analytisch", "Teamplayer", "Führungspersönlichkeit"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "multiChoice",
        title: "Wie triffst du Entscheidungen?",
        elements: [
          { id: "el-1", type: "radio", options: ["Mit dem Bauch", "Datenbasiert", "Im Team", "Spontan"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-4",
        type: "contact",
        title: "Fast geschafft!",
        subtitle: "Wohin sollen wir dein Ergebnis senden?",
        elements: [
          { id: "el-1", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "Ergebnis anzeigen",
      },
      {
        id: "page-5",
        type: "thankyou",
        title: "Du bist ein Innovator!",
        subtitle: "Check deine E-Mail für mehr Details",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#10B981",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-recruiting",
    name: "Schnell-Bewerbung",
    description: "Finde Top-Talente mit einem mobilen Bewerbungs-Funnel",
    category: "recruiting",
    thumbnail: "/templates/recruiting.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Werde Teil unseres Teams!",
        subtitle: "Bewirb dich in unter 2 Minuten",
        elements: [],
        buttonText: "Jetzt bewerben",
        backgroundColor: "#F59E0B",
      },
      {
        id: "page-2",
        type: "question",
        title: "Welche Position interessiert dich?",
        elements: [
          { id: "el-1", type: "radio", options: ["Vertrieb", "Marketing", "Entwicklung", "Kundenservice"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "question",
        title: "Wie viel Erfahrung bringst du mit?",
        elements: [
          { id: "el-1", type: "radio", options: ["0-1 Jahre", "2-5 Jahre", "5+ Jahre"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-4",
        type: "contact",
        title: "Deine Kontaktdaten",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
          { id: "el-3", type: "input", placeholder: "Deine Telefonnummer", required: true },
          { id: "el-4", type: "textarea", placeholder: "Erzähl uns kurz von dir..." },
        ],
        buttonText: "Bewerbung absenden",
      },
      {
        id: "page-5",
        type: "thankyou",
        title: "Bewerbung erhalten!",
        subtitle: "Wir melden uns in den nächsten Tagen bei dir",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#F59E0B",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-sales",
    name: "Produkt-Verkauf",
    description: "Verkaufe deine Produkte oder Dienstleistungen direkt",
    category: "sales",
    thumbnail: "/templates/sales.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Exklusives Angebot",
        subtitle: "Nur für kurze Zeit verfügbar",
        elements: [],
        buttonText: "Angebot ansehen",
        backgroundColor: "#DC2626",
      },
      {
        id: "page-2",
        type: "question",
        title: "Welches Paket passt zu dir?",
        elements: [
          { id: "el-1", type: "radio", options: ["Starter - 49€", "Professional - 99€", "Enterprise - 199€"] },
        ],
        buttonText: "Auswählen",
      },
      {
        id: "page-3",
        type: "contact",
        title: "Deine Bestelldaten",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "Jetzt bestellen",
      },
      {
        id: "page-4",
        type: "thankyou",
        title: "Bestellung erfolgreich!",
        subtitle: "Du erhältst gleich eine Bestätigung per E-Mail",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#DC2626",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-ebook",
    name: "E-Book Download",
    description: "Verteile dein E-Book oder Whitepaper an Interessenten",
    category: "leads",
    thumbnail: "/templates/ebook.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Kostenloses E-Book",
        subtitle: "Lerne die 10 Geheimnisse erfolgreicher Unternehmer",
        elements: [],
        buttonText: "Jetzt herunterladen",
        backgroundColor: "#8B5CF6",
      },
      {
        id: "page-2",
        type: "contact",
        title: "Wohin sollen wir es senden?",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "E-Book anfordern",
      },
      {
        id: "page-3",
        type: "thankyou",
        title: "E-Book unterwegs!",
        subtitle: "Check deine E-Mail für den Download-Link",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#8B5CF6",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-event",
    name: "Event-Anmeldung",
    description: "Registrierungen für dein nächstes Event sammeln",
    category: "webinar",
    thumbnail: "/templates/event.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Exklusives Event",
        subtitle: "Sei live dabei am 15. März 2025",
        elements: [],
        buttonText: "Ticket sichern",
        backgroundColor: "#EC4899",
      },
      {
        id: "page-2",
        type: "question",
        title: "Welches Ticket möchtest du?",
        elements: [
          { id: "el-1", type: "radio", options: ["Standard - Kostenlos", "VIP - 49€", "Backstage - 149€"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "contact",
        title: "Deine Daten",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
          { id: "el-3", type: "input", placeholder: "Telefon (optional)" },
        ],
        buttonText: "Anmelden",
      },
      {
        id: "page-4",
        type: "thankyou",
        title: "Du bist angemeldet!",
        subtitle: "Dein Ticket kommt per E-Mail",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#EC4899",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-feedback",
    name: "Kundenfeedback",
    description: "Sammle wertvolles Feedback von deinen Kunden",
    category: "quiz",
    thumbnail: "/templates/feedback.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Deine Meinung zählt!",
        subtitle: "Hilf uns, besser zu werden",
        elements: [],
        buttonText: "Feedback geben",
        backgroundColor: "#06B6D4",
      },
      {
        id: "page-2",
        type: "multiChoice",
        title: "Wie zufrieden bist du?",
        elements: [
          { id: "el-1", type: "radio", options: ["Sehr zufrieden", "Zufrieden", "Neutral", "Unzufrieden"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "question",
        title: "Was können wir verbessern?",
        elements: [
          { id: "el-1", type: "textarea", placeholder: "Dein Feedback..." },
        ],
        buttonText: "Absenden",
      },
      {
        id: "page-4",
        type: "thankyou",
        title: "Vielen Dank!",
        subtitle: "Dein Feedback hilft uns sehr",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#06B6D4",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-newsletter",
    name: "Newsletter-Anmeldung",
    description: "Baue deine E-Mail-Liste auf",
    category: "leads",
    thumbnail: "/templates/newsletter.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Bleib auf dem Laufenden!",
        subtitle: "Erhalte exklusive Tipps direkt in dein Postfach",
        elements: [],
        buttonText: "Anmelden",
        backgroundColor: "#3B82F6",
      },
      {
        id: "page-2",
        type: "contact",
        title: "Trag dich ein",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Vorname", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "Jetzt anmelden",
      },
      {
        id: "page-3",
        type: "thankyou",
        title: "Willkommen!",
        subtitle: "Du bist jetzt Teil unserer Community",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#3B82F6",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-waitlist",
    name: "Warteliste",
    description: "Sammle Interessenten für deinen Launch",
    category: "leads",
    thumbnail: "/templates/waitlist.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Coming Soon",
        subtitle: "Sei unter den Ersten, die es erfahren",
        elements: [],
        buttonText: "Auf die Warteliste",
        backgroundColor: "#1F2937",
      },
      {
        id: "page-2",
        type: "contact",
        title: "Sichere dir deinen Platz",
        elements: [
          { id: "el-1", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "Eintragen",
      },
      {
        id: "page-3",
        type: "thankyou",
        title: "Du bist auf der Liste!",
        subtitle: "Wir benachrichtigen dich als Erstes",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#1F2937",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-contest",
    name: "Gewinnspiel",
    description: "Steigere Engagement mit einem Gewinnspiel",
    category: "leads",
    thumbnail: "/templates/contest.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Gewinne tolle Preise!",
        subtitle: "Nimm jetzt am Gewinnspiel teil",
        elements: [],
        buttonText: "Mitmachen",
        backgroundColor: "#EAB308",
      },
      {
        id: "page-2",
        type: "question",
        title: "Beantworte diese Frage:",
        subtitle: "Welches Produkt gefällt dir am besten?",
        elements: [
          { id: "el-1", type: "radio", options: ["Produkt A", "Produkt B", "Produkt C"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "contact",
        title: "Fast geschafft!",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
        ],
        buttonText: "Teilnehmen",
      },
      {
        id: "page-4",
        type: "thankyou",
        title: "Viel Glück!",
        subtitle: "Die Gewinner werden per E-Mail benachrichtigt",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#EAB308",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-coaching",
    name: "Coaching-Programm",
    description: "Gewinne Teilnehmer für dein Coaching",
    category: "sales",
    thumbnail: "/templates/coaching.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Erreiche deine Ziele",
        subtitle: "Mit unserem bewährten Coaching-Programm",
        elements: [],
        buttonText: "Mehr erfahren",
        backgroundColor: "#059669",
      },
      {
        id: "page-2",
        type: "multiChoice",
        title: "Was ist dein Hauptziel?",
        elements: [
          { id: "el-1", type: "radio", options: ["Karriere voranbringen", "Mehr verdienen", "Work-Life-Balance", "Selbstständigkeit"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "question",
        title: "Wann möchtest du starten?",
        elements: [
          { id: "el-1", type: "radio", options: ["Sofort", "In 1-2 Wochen", "Nächsten Monat"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-4",
        type: "contact",
        title: "Kostenlose Beratung",
        subtitle: "Lass uns unverbindlich sprechen",
        elements: [
          { id: "el-1", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-2", type: "input", placeholder: "Deine E-Mail", required: true },
          { id: "el-3", type: "input", placeholder: "Telefon", required: true },
        ],
        buttonText: "Termin buchen",
      },
      {
        id: "page-5",
        type: "thankyou",
        title: "Anfrage erhalten!",
        subtitle: "Wir melden uns innerhalb von 24h bei dir",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#059669",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-service",
    name: "Dienstleistungs-Anfrage",
    description: "Generiere qualifizierte Anfragen für deine Services",
    category: "leads",
    thumbnail: "/templates/service.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Professionelle Lösung",
        subtitle: "Für dein Projekt",
        elements: [],
        buttonText: "Anfrage starten",
        backgroundColor: "#6366F1",
      },
      {
        id: "page-2",
        type: "question",
        title: "Welche Leistung brauchst du?",
        elements: [
          { id: "el-1", type: "radio", options: ["Beratung", "Umsetzung", "Beides"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "question",
        title: "Budget-Rahmen?",
        elements: [
          { id: "el-1", type: "radio", options: ["Unter 1.000€", "1.000 - 5.000€", "5.000 - 10.000€", "Über 10.000€"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-4",
        type: "contact",
        title: "Kontaktdaten",
        elements: [
          { id: "el-1", type: "input", placeholder: "Firma", required: true },
          { id: "el-2", type: "input", placeholder: "Ansprechpartner", required: true },
          { id: "el-3", type: "input", placeholder: "E-Mail", required: true },
          { id: "el-4", type: "textarea", placeholder: "Projektbeschreibung" },
        ],
        buttonText: "Anfrage senden",
      },
      {
        id: "page-5",
        type: "thankyou",
        title: "Anfrage gesendet!",
        subtitle: "Wir erstellen dir ein individuelles Angebot",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#6366F1",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-research",
    name: "Marktforschung",
    description: "Sammle Insights von deiner Zielgruppe",
    category: "quiz",
    thumbnail: "/templates/research.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Deine Meinung ist gefragt!",
        subtitle: "Hilf uns mit einer kurzen Umfrage",
        elements: [],
        buttonText: "Umfrage starten",
        backgroundColor: "#0EA5E9",
      },
      {
        id: "page-2",
        type: "multiChoice",
        title: "Wie oft nutzt du solche Produkte?",
        elements: [
          { id: "el-1", type: "radio", options: ["Täglich", "Wöchentlich", "Monatlich", "Selten"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "multiChoice",
        title: "Was ist dir am wichtigsten?",
        elements: [
          { id: "el-1", type: "radio", options: ["Preis", "Qualität", "Service", "Schnelligkeit"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-4",
        type: "question",
        title: "Noch Anmerkungen?",
        elements: [
          { id: "el-1", type: "textarea", placeholder: "Deine Gedanken..." },
        ],
        buttonText: "Absenden",
      },
      {
        id: "page-5",
        type: "thankyou",
        title: "Danke fürs Mitmachen!",
        subtitle: "Dein Feedback ist sehr wertvoll für uns",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#0EA5E9",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
  {
    id: "template-demo",
    name: "Produkt-Demo",
    description: "Demo-Anfragen für dein Produkt sammeln",
    category: "sales",
    thumbnail: "/templates/demo.png",
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Entdecke die Möglichkeiten",
        subtitle: "Buche deine persönliche Demo",
        elements: [],
        buttonText: "Demo anfordern",
        backgroundColor: "#7C3AED",
      },
      {
        id: "page-2",
        type: "question",
        title: "Unternehmensgröße?",
        elements: [
          { id: "el-1", type: "radio", options: ["1-10 Mitarbeiter", "11-50 Mitarbeiter", "51-200 Mitarbeiter", "200+ Mitarbeiter"] },
        ],
        buttonText: "Weiter",
      },
      {
        id: "page-3",
        type: "contact",
        title: "Demo-Termin buchen",
        elements: [
          { id: "el-1", type: "input", placeholder: "Firma", required: true },
          { id: "el-2", type: "input", placeholder: "Dein Name", required: true },
          { id: "el-3", type: "input", placeholder: "E-Mail", required: true },
          { id: "el-4", type: "input", placeholder: "Telefon" },
        ],
        buttonText: "Demo buchen",
      },
      {
        id: "page-4",
        type: "thankyou",
        title: "Demo gebucht!",
        subtitle: "Wir senden dir die Termin-Details per E-Mail",
        elements: [],
      },
    ],
    theme: {
      primaryColor: "#7C3AED",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  },
];

export function getTemplateById(id: string): Template | undefined {
  return defaultTemplates.find(t => t.id === id);
}

export function getTemplatesByCategory(category: Template["category"]): Template[] {
  return defaultTemplates.filter(t => t.category === category);
}

export function createBlankFunnel(): { pages: FunnelPage[], theme: Template["theme"] } {
  return {
    pages: [
      {
        id: "page-1",
        type: "welcome",
        title: "Willkommen",
        subtitle: "Füge hier deinen Untertitel ein",
        elements: [],
        buttonText: "Weiter",
        backgroundColor: "#7C3AED",
      },
    ],
    theme: {
      primaryColor: "#7C3AED",
      backgroundColor: "#ffffff",
      textColor: "#1a1a1a",
      fontFamily: "Inter",
    },
  };
}
