import { test, expect } from "@playwright/test";
import { registerAndVerify, createPublishedFunnel, getCsrfToken } from "./helpers/api";
import { closePool } from "./helpers/db";
import { makeSlug, runId } from "./helpers/unique";
test.afterAll(closePool);
test("AI proposals are reviewed before applying and preserve button links", async ({ page, request }) => {
  await page.addInitScript(() => { localStorage.setItem("onboarding-completed", "true"); localStorage.setItem("trichterwerk-cookie-consent", "true"); });
  await registerAndVerify(page.request);
  const funnel = await createPublishedFunnel(page.request, { name: "KI-Texte", slug: makeSlug(runId()) });
  const original = "Jetzt ausführliche Informationen unverbindlich anfordern";
  const owner = await (await page.request.get(`/api/funnels/${funnel.id}`)).json();
  owner.pages[0].elements = [{ id: "ai-button", type: "button", content: original, buttonAction: "url", buttonUrl: "https://example.test/info" }];
  const csrf = await getCsrfToken(page.request);
  expect((await page.request.patch(`/api/funnels/${funnel.id}`, { headers: { "X-CSRF-Token": csrf }, data: { pages: owner.pages, expectedVersion: owner.editVersion, documentVersion: 1, mutationId: crypto.randomUUID(), publish: true } })).ok()).toBeTruthy();
  const payload = { intent: "shorten", items: [{ id: "ai-button", type: "button", content: original }] };
  const noKey = await page.request.post(`/api/funnels/${funnel.id}/ai/rewrite`, { headers: { "X-CSRF-Token": csrf }, data: payload });
  expect(noKey.status()).toBe(400); expect((await noKey.json()).code).toBe("AI_NO_KEY");
  await registerAndVerify(request);
  expect((await request.post(`/api/funnels/${funnel.id}/ai/rewrite`, { headers: { "X-CSRF-Token": await getCsrfToken(request) }, data: payload })).status()).toBe(404);
  await page.route(`**/api/funnels/${funnel.id}/ai/rewrite`, route => { expect(route.request().postDataJSON().items).toEqual(payload.items); return route.fulfill({ json: { suggestions: [{ id: "ai-button", variants: ["Jetzt Infos anfordern"] }] } }); });
  await page.goto(`/funnels/${funnel.id}`);
  await page.locator('[data-funnel-element="ai-button"]').click();
  await page.getByRole("button", { name: "Mit KI bearbeiten" }).click();
  await page.getByRole("button", { name: "Vorschläge erstellen", exact: true }).click();
  await expect(page.getByRole("dialog")).toContainText("Jetzt Infos anfordern");
  await expect(page.locator('[data-funnel-element="ai-button"]')).toContainText(original);
  await page.getByRole("button", { name: "Vorschlag 1 übernehmen" }).click();
  await page.keyboard.press("Escape");
  await expect(page.locator('[data-funnel-element="ai-button"]')).toContainText("Jetzt Infos anfordern");
  await page.getByTestId("button-save").click();
  await expect(page.getByText(/Gespeichert/).first()).toBeVisible();
  const draft = await (await page.request.get(`/api/funnels/${funnel.id}`)).json();
  expect(draft.pages[0].elements[0]).toMatchObject({ content: "Jetzt Infos anfordern", buttonUrl: "https://example.test/info", buttonAction: "url" });
  expect((await (await page.request.get(`/api/public/funnels/${funnel.slug}`)).json()).pages[0].elements[0].content).toBe(original);
});
