import { test, expect } from "@playwright/test";
import { registerAndVerify, createPublishedFunnel, getCsrfToken } from "./helpers/api";
import { closePool } from "./helpers/db";
import { makeSlug, runId } from "./helpers/unique";
test.afterAll(closePool);
test("compares live and draft without publishing, submitting or exposing other owners' revisions", async ({ page, request }) => {
  await page.addInitScript(() => { localStorage.setItem("onboarding-completed", "true"); localStorage.setItem("trichterwerk-cookie-consent", "true"); });
  await registerAndVerify(page.request);
  const funnel = await createPublishedFunnel(page.request, { name: "Vergleich", slug: makeSlug(runId()) });
  const headers = { "X-CSRF-Token": await getCsrfToken(page.request) };
  let owner = await (await page.request.get(`/api/funnels/${funnel.id}`)).json();
  owner.pages[0].elements = [{ id: "title", type: "heading", content: "Veröffentlichter Text" }];
  const live = await page.request.patch(`/api/funnels/${funnel.id}`, { headers, data: { pages: owner.pages, expectedVersion: owner.editVersion, documentVersion: 1, mutationId: crypto.randomUUID(), publish: true } });
  expect(live.ok()).toBeTruthy(); owner = await live.json();
  owner.pages[0].elements[0].content = "Geänderter Entwurf";
  expect((await page.request.patch(`/api/funnels/${funnel.id}`, { headers, data: { pages: owner.pages, expectedVersion: owner.editVersion, documentVersion: 1, mutationId: crypto.randomUUID() } })).ok()).toBeTruthy();
  const publicCalls: string[] = [];
  page.on("request", req => { if (/\/api\/public\/(analytics|leads)/.test(req.url())) publicCalls.push(req.url()); });
  await page.goto(`/funnels/${funnel.id}`);
  await page.getByTestId("button-publish").click();
  await page.getByRole("button", { name: "Mit Live-Stand vergleichen" }).click();
  await expect(page.getByTestId("comparison-before")).toContainText("Veröffentlichter Text");
  await expect(page.getByTestId("comparison-draft")).toContainText("Geänderter Entwurf");
  await expect(page.getByTestId("revision-comparison")).toContainText("Geändert: Willkommen: Geänderter Entwurf");
  expect(publicCalls).toEqual([]);
  expect((await (await page.request.get(`/api/public/funnels/${funnel.slug}`)).json()).pages[0].elements[0].content).toBe("Veröffentlichter Text");
  await page.getByTestId("comparison-draft").scrollIntoViewIfNeeded();
  await page.screenshot({ path: "/tmp/trichterwerk-improvements-tests/comparison.png" });
  const snapshot = await (await page.request.get(`/api/funnels/${funnel.id}/revisions/published`)).json();
  expect(snapshot.content.webhookSecret).toBeUndefined();
  await registerAndVerify(request);
  expect((await request.get(`/api/funnels/${funnel.id}/revisions/${snapshot.id}`)).status()).toBe(404);
  expect((await request.get(`/api/funnels/${funnel.id}/revisions/published`)).status()).toBe(404);
});
